### ISSUE TITLE
Fix website favicon

### ISSUE THREAD

**Issue by thecodeah** [thecodeah/secret-board#9]
Currently uses a SVG. I assume not all browsers accept SVG's as favicons. Add PNG version of favicon.

Please make these changes on the `development` branch!!!

**Comment by dmoneyballer** [comment]
I'll upload a png to the dev branch shortly

**Comment by dmoneyballer** [comment]
I've created a pull request #11

**Comment by dmoneyballer** [comment]
I've added it in the base.html. Does that work? I'm having trouble running it though. I have the docker container running and when I check my localhost:8000 I get a connection refused. same when I curl it.

**Comment by thecodeah** [comment]
The website uses port 80, make sure you use docker-compose.

Anyways, I've just tested it and it works :+1: 
![image](https://user-images.githubusercontent.com/21268739/66268630-8c8ac880-e83f-11e9-9830-a5de670311bf.png)

**Comment by thecodeah** [comment]
Issue resolved with #11
